
const GET_CATEGORY = 'GET_CATEGORY';
const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';
const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
const ADD_CATEGORY = 'ADD_CATEGORY';

export {
    GET_CATEGORY,
    GET_CATEGORY_ERROR,
    GET_CATEGORY_SUCCESS,
    ADD_CATEGORY,
}